### PR TITLE
Roid outpost

### PR DESCRIPTION
**Pull request by mkanke-real**
## About the PR

Adds a new low-mid pop map to the game. Nestled inside an asteroid it is a very cozy map made to be compact and very quick to navigate. Some departments may be smaller than you expect but will be fully featured, just dont expect lots of elbow room. Deep in the maintenance halls there is a small airlock leading into the asteroid interior so you can mine and expand the station to your hearts content.
## Why / Balance

We just really needed a new ultra-lowpop map so theres more choices than just Reach and Saltern when the server is getting rolling again or if people just want a concentrated experience.
## Technical details

Adds new map files into the maps and prototypes folder and adds it to the map pool but not rotation.
## Media

Roid Food Court

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: 
- add: New map Roid to the map pool.

### CODE REVIEW

**Comment by taydeo** [comment]
Add your map to the tests in that file.

**Comment by taydeo** [comment]
Do not include the Brigmedic prototype in the YAML, just the spawners in the actual map.
image

**Comment by taydeo** [comment]
image
Look for any "invalid" tags in the map file. Remove them.

**Comment by mkanke-real** [comment]
Who is Amussa-Dooka and why are they making my test fail >:( Really though that name isnt in my file at all and I have never used in dev mode a character named that. Is this just a test bug?

**Comment by mkanke-real** [comment]
Added actual PR info now to the description.

**Comment by taydeo** [comment]
image
Heres whats breaking it. Look at the entity info on the YAML file.

**Comment by mkanke-real** [comment]
> image Heres whats breaking it. Look at the entity info on the YAML file.

Well I see what happened. When checking some devices I saved the map after a client crash BUT I was holding the network configurer so it poofed out of existence. Which means I now need to redo all the airlock wiring I believe. Very suboptimal but it is what it is. Well time to get at it.

**Comment by taydeo** [comment]
No you don't. You just go into the YAML file of the map and search up "invalid", then delete any references.

**Pull request closed without merging**
