### PR TITLE
Updated glacier

### PR DESCRIPTION
**Pull request by Aineias1**
…added station anchor

## About the PR

Added station anchor, replaced some asteroid walls with normal wall for department security
## Why / Balance

anyone could get in sec with a pickaxe
## Media

None, no major additions for media
## Requirements

- [ x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Updated glacier

### CODE REVIEW

**Comment by taydeo** [comment]
Be sure to update your changelog description in the PR, so you can get your credit in game.

**Comment by Aineias1** [comment]
> Be sure to update your changelog description in the PR, so you can get your credit in game.

the changes are so small so eh

**Comment by taydeo** [comment]
nah you deserve credit

**Comment by Aineias1** [comment]
> nah you deserve credit

i actually forgot to remove <-- --> lmao

**Pull request merged**
