### PR TITLE
Roboticist Mapping

### PR DESCRIPTION
**Pull request by NkoKirkto**
## About the PR
-Added Roboticists Spawns to every Map in the Game
-Changed the Airlocks to the right ones
-Removed all the Robotics Wardrobes and replaced them with the Roboticist Locker
-Changed the Protos so that it points to the changed maps

## Why / Balance
Tayedo already explained that in his PR funky-station/funky-station#217

## Technical details
Just changed where the prototypes point and added the Roboticists to the Maps

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: The Roboticists are now Playable and Robotics Is updated

### CODE REVIEW

**Comment by taydeo** [comment]
image
comment fail

**Comment by taydeo** [comment]
also change your CL to be more reflective of what you actually changed

something like "added roboticist spawns to all maps in the game"

**Comment by taydeo** [comment]
image
WAIT WHAT?

**Comment by taydeo** [comment]
image
Ohhhh nvm

**Comment by NkoKirkto** [comment]
> image WAIT WHAT?

You said to move all the map ymls to _Funkystation. That is what i did.

**Comment by taydeo** [comment]
> > image WAIT WHAT?
> 
> You said to move all the map ymls to _Funkystation. That is what i did.

https://github.com/funky-station/funky-station/pull/219#issuecomment-2561983563

**Pull request merged**
