### PR TITLE
Dawn Plushie again

### PR DESCRIPTION
**Pull request by RetroManb**
## About the PR

I added the Dawn Leander plushy™, it screams and laughs. Right now it can can only be obtained from maintenance lockers, plushy crates, and by buying the bulk dawn plushie crate from Cargo.

## Why / Balance

Becuase it's funny

## Technical details

 
None

## Media

image
AAAAAAAAAAAAAAAAAAAA

## Requirements

- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None

**Changelog**

:cl:
- add: Added the Dawn Leander plushy.

### CODE REVIEW

**Comment by RetroManb** [comment]
"I was going to make it so that you can buy them from Cargo, but it felt like a bit much, I'll probably end up doing that at some other point." actually let me do this

**Comment by taydeo** [comment]
Hi, I've figured out how to add them to the general plushie pool, look at this commit here. https://github.com/funky-station/funky-station/commit/83495612d1417bba26d3d6cddc0a31b1db8d2628. Also, make a separate RSI for this as the Cirno plushie is a nonstandard size.

**Comment by taydeo** [comment]
also, it looks very cute, thanks a bunch

**Comment by RetroManb** [comment]
ok i think everything is ok now

**Comment by RetroManb** [comment]
ok now everything should be ok 🙏🏾

**Comment by RetroManb** [comment]
now now everything should be ok

**Pull request merged**
