### PR TITLE
Aloxadone buffed to the original vision

### PR DESCRIPTION
**Pull request by Rainbeon**
## About the PR
Buffed Aloxadone to what I had wanted it to be originally. Boosting it's heat healing from 3 to 5, and changing the recipe to be less costly.

## Why / Balance
Aloxadone was originally made very expensive by me to appeal to WizDen maintainers, even if it made it fairly annoying to actually make and use. This buffs it to how near what I had originally envisioned it to be.

## Media
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Aloxadone now heals 5 heat damage, up from 3.
- tweak: Aloxadone's recipe has been buffed to be 20u Aloe, 20u Sigynate, and 60u Cryoxadone for 100u Aloxadone. This results in 2.5x more product per resource intensive ingredient.

### CODE REVIEW

**Comment by taydeo** [comment]
Hi

**Comment by Rainbeon** [comment]
hey!

**Comment by Rainbeon** [comment]
noh

**Comment by taydeo** [comment]
Ok

**Pull request merged**
