### PR TITLE
Adds a lobby screen for Foxei

### PR DESCRIPTION
**Pull request by Erisiaa**
## About the PR

Added a lobby screen
## Why / Balance

did it for Foxei because they didn't know how to make a pr, and I wanted to learn.
## Technical details

took code from other lobby screens
## Media

https://cdn.discordapp.com/attachments/1306117030176493610/1309257353656275004/funkystationcrew.webp?ex=6740ec6d&is=673f9aed&hm=d54d15388fe7db8d95e46e659dc8edaba14cfd8e314e5c9fe7e975cd61c3c9cb&
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

shouldn't be any breaking changes (I hope) 
**Changelog**

:cl:
-Adds a lobby screen made by Foxei

### CODE REVIEW

**Comment by taydeo** [comment]
add the rest of the stuff

**Comment by taydeo** [comment]
like the

:cl:
- add: awdjusahjkadsg

**Comment by JohnnyDangerSpace** [comment]
FIX YOUR CHECKS!!!

**Comment by Erisiaa** [comment]
uhhh

**Comment by Erisiaa** [comment]
how do I fix this shit

**Review by GroggleG — COMMENTED** [review]
Missing the webp.yml for it.

**Comment by Erisiaa** [comment]
closing for now

**Pull request closed without merging**
