### PR TITLE
Functional SmartFridge

### PR DESCRIPTION
**Pull request by taydeo**
## About the PR
Adds a functional SmartFridge, where things like pill canisters, individual pills, food, and raw meat can be stored.

## Why / Balance
This is part of a multi-feature update that gives medical appropriate tools to organize themselves in preparation of a rework with Chemistry. Other departments may benefit from this.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

If Wizden ever updates the SmartFridge

**Changelog**

:cl:
- add: The SmartFridge™, feature complete with methods to store pills, jugs, and perishables.

### CODE REVIEW

**Comment by BombasterDS** [comment]
i think one Container of items EntityUid with Dictionary<SmartFridgeInventoryItem, List<EntityUid>> should work better than bunch of itemSlots. (Not sure if i understand inserting logic correctly, but as i can understand you using vendingMachine logic, so it might work with slots)

**Comment by taydeo** [comment]
From what I understand, using the ItemSlotsManager system requires it to have a bunch of those slots, since each one is named uniquely. I've thought about doing it a different way (involving some garbage with inventories or whatever), but this way seemed the most straight forward.

**Comment by taydeo** [comment]
test fail seems to be unrelated

**Comment by taydeo** [comment]
Fuck it self merge

**Pull request merged**
